AccountsApp/config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get 'login/index'
  get 'login/login_check'
  get 'category_config/index'
  get 'postdata/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  # post 'home/index'
  post "home/index/", to: "home#create"
  patch "home/index/", to: "home#create"
  get 'home/history'
  post 'home/history'
  get "home/edit/:id", to: "home#edit"
  patch "home/edit/:id", to: "home#update"
  get "home/delete/:id", to: "home#delete"
  get "category/index", to: 'category_config#index'
  get "change_ctg", to: 'home#change_ctg'
  get "change_month", to: 'home#change_month'
  post "change_month", to: 'home#change_month'
  post "change_month_chart", to: 'home#change_month_chart'
  get "home/grid_input", to: "home#grid_input"
end

AccountsApp/app/controllers/login_controller.rb
class LoginController < ApplicationController
    before_action :authenticate_account!

    def index
        @msg = "login page"
    end

    def login_check
        @account = current_account
        # @msg = "you logined at: "+ @account.current_sign_in_at.to_s
        @msg = "you logined at: "+ @account.id.to_s
    end
end

AccountsApp/app/helpers/login_helper.rb
module LoginHelper
end

AccountsApp/app/views/login/index.html.erb
<h1>welcome</h1>
<p>
    <%= @msg %>
</p>
<hr>
<div>
    <%=link_to "go to login_check page!&gt;&gt;" .html_safe, {action: "login_check"} %>
</div>
<div>
    <%=link_to "Sign out&gt;&gt;" .html_safe, destroy_account_session_path, method: :delete %>
</div>

AccountsApp/app/views/login/login_check.html.erb
<h1>
    <%= @account.email %>
</h1>
<p>
    <%= @msg %>
</p>